# Generated by Django 3.2.5 on 2021-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='link_picture',
            field=models.CharField(default='no informado', max_length=200),
            preserve_default=False,
        ),
    ]
