# Generated by Django 3.2.5 on 2021-07-27 01:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('hello', '0004_auto_20210716_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('Diseño / UX', 'Diseño / UX'), ('Programación', 'Programación'), ('Data Science / Analytics', 'Data Science / Analytics'), ('Desarrollo Mobile', 'Desarrollo Mobile'), ('Servicio al Cliente', 'Servicio al Cliente'), ('Marketing Digital', 'Marketing Digital'), ('SysAdmin / DevOps / QA', 'SysAdmin / DevOps / QA'), ('Operaciones / Management', 'Operaciones / Management'), ('Comercial y Ventas', 'Comercial y Ventas'), ('Publicidad y Medios', 'Publicidad y Medios'), ('Innovación y Agilidad', 'Innovación y Agilidad'), ('Recursos Humanos', 'Recursos Humanos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
